scripts/ipfs-gw: update the path of ipfs-gateway-result.log

diff --git a/scripts/ipfs-gw b/scripts/ipfs-gw
--- a/scripts/ipfs-gw
+++ b/scripts/ipfs-gw
@@ -8,7 +8,10 @@ then
     exit 0
 fi
 
-RES_FILE="/tmp/ipfs-gateway-result.log"
+SELF_PATH=$(dirname $0)
+RES_FILE="$SELF_PATH/../../csobot/ipfs-gateway-result.log"
+[[ -f $RES_FILE ]] || echo "Oops, the list is not found."
+
 echo "==== Today's IPFS gateway: ===="
 cat $RES_FILE
 
