scripts/ipfs-add: finalised

diff --git a/scripts/ipfs-add b/scripts/ipfs-add
--- a/scripts/ipfs-add
+++ b/scripts/ipfs-add
@@ -10,7 +10,7 @@ fi
 
 URL="$1"
 URL_FILE="${URL##*/}"
-TMP=/tmp/csobot-ipfs/
+TMP=/tmp/csobot-ipfs
 mkdir -p $TMP
 ret=0
 ret_final=0
@@ -18,27 +18,30 @@ HOME=/home/user
 PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin
 
 IPFS_GW="
+https://ipfs.eternum.io/ipfs
+https://gateway.ipfs.io/ipfs
+https://ipfs.io/ipfs
+https://cloudflare-ipfs.com/ipfs
 https://ipfs.sloppyta.co/ipfs
-https://d26g9c7mfuzstv.cloudfront.net/ipfs
 "
 
 # Find out ipfs binary.
-#IPFS=$(/usr/bin/which ipfs 2>/dev/null)
-#if [[ -z $IPFS ]]; then
+IPFS=$(/usr/bin/which ipfs 2>/dev/null)
+if [[ -z $IPFS ]]; then
 	IPFS=$HOME/go-ipfs/ipfs
-#fi
-#
+fi
+
 CURL=$(/usr/bin/which curl 2>/dev/null)
-#if [[ -z $CURL ]]; then
-#	echo "Oops, could not find cURL tool!"
-#	exit 1
-#fi
+if [[ -z $CURL ]]; then
+	echo "Oops, could not find cURL tool!"
+	exit 1
+fi
 	
 # Check if ipfs is running.
-#if ! (ps -ef |grep go-ipfs/ipfs |grep -v grep >/dev/null); then
-#	($IPFS daemon) &
-#	sleep 5
-#fi
+if ! (ps -ef |grep go-ipfs/ipfs |grep -v grep >/dev/null); then
+	($IPFS daemon) &
+	sleep 5
+fi
 
 # Request the url.
 echo ">> Downloading you webpage..."
@@ -51,9 +54,9 @@ sleep 1
 if [[ $ret -eq 0 ]]; then
 	echo ">> Adding and pinning it to IPFS..."
 	FILE_HASH=$($IPFS add $TMP/$URL_FILE  | /usr/bin/head -n1 | /usr/bin/awk '{ print $2 }')
-	echo "Hash: $FILE_HASH"
+	#echo "Hash: $FILE_HASH"
 	sleep 1
-	echo "$IPFS pin add $FILE_HASH"
+	#echo "$IPFS pin add $FILE_HASH"
 	ret_pin=$($IPFS pin add $FILE_HASH) || ret_final=1
 else
 	echo "Oops, FAIL to download the webpage you request!"
@@ -62,10 +65,12 @@ fi
 
 # Return the hash along with the gateway urls.
 if [[ $ret_final -eq 0 ]]; then
-	echo -e "\nCongrats! The IPFS addresses of the webpage you request are:"
+	echo "==============================="
+	echo -e "Congrats! The IPFS addresses of the webpage you request are:"
 	for gw in $IPFS_GW; do
 		echo "${gw}/$FILE_HASH"
 	done
+	echo "==============================="
 	exit
 else
 	echo "Oops, FAIL to pin the webpage you request!"
